"""writ-agent — official Python SDK for the Writ local agent (writ-agentd).

Quickstart::

    from writ_agent import WritAgent, run_row_id

    with WritAgent() as client:            # discovers the local daemon
        for wf in client.workflows.list():
            print(wf["id"], wf["name"])
        run = client.workflows.run_and_wait(3, inputs={"city": "Paris"})
        print(run["status"], client.runs.data(run_row_id(run))["data"])

See the package README for the full surface, discovery, and error handling.
"""

from ._version import __version__
from .async_client import AsyncWritAgent
from .client import WritAgent
from .cloud import (
    TERMINAL_BUILD_STATUSES,
    AsyncCloud,
    AsyncCloudBuilds,
    AsyncCloudAutomations,
    AsyncCloudMonitors,
    AsyncCloudPersonas,
    Cloud,
    CloudAutomations,
    CloudBuilds,
    CloudMonitors,
    CloudPersonas,
)
from .errors import (
    WritApiError,
    WritApiKeyRequiredError,
    WritConnectionError,
    WritDiscoveryError,
    WritError,
    WritInsufficientCreditsError,
    WritPlanLimitError,
    WritRateLimitedError,
    WritRunTimeoutError,
    WritTimeoutError,
)
from ._retry import DEFAULT_RETRY, RetryPolicy
from ._watch import watch_changes, watch_changes_async
from .pagination import DEFAULT_AUTO_PAGE_SIZE, Page, auto_page, auto_page_async
from .webhooks import (
    DEFAULT_TOLERANCE_SECONDS,
    SIGNATURE_HEADER,
    SIGNATURE_V1_HEADER,
    TIMESTAMP_HEADER,
    WritWebhookVerificationError,
    sign_webhook_request,
    verify_webhook,
)
from .types import (
    TERMINAL_EVENTS,
    AgentHealth,
    AgentStatus,
    ApiKey,
    Automation,
    CancelResult,
    CacheStamp,
    CrawlDataTable,
    CrawlDefinition,
    CrawlDefinitionList,
    CrawlJob,
    CrawlList,
    CrawlStartBody,
    CrawlStatus,
    SavedCrawlData,
    SavedCrawlRun,
    Dataset,
    DatasetList,
    ErrorEvent,
    Extractor,
    FileSlot,
    FinishedEvent,
    Monitor,
    OutputFile,
    MonitorHistory,
    Persona,
    ProgressEvent,
    RecentChange,
    RunData,
    RunEvent,
    RunFeedItem,
    RunResults,
    RunCompleted,
    RunStarted,
    SecretMeta,
    Selector,
    StartedEvent,
    StepEvent,
    StoredFile,
    VaultStatus,
    Workflow,
    WsTicket,
    file_slots,
    output_files,
    run_row_id,
)

__all__ = [
    "__version__",
    "WritAgent",
    "AsyncWritAgent",
    "Page",
    # production helpers
    "RetryPolicy",
    "DEFAULT_RETRY",
    "auto_page",
    "auto_page_async",
    "DEFAULT_AUTO_PAGE_SIZE",
    "watch_changes",
    "watch_changes_async",
    "verify_webhook",
    "sign_webhook_request",
    "WritWebhookVerificationError",
    "SIGNATURE_HEADER",
    "SIGNATURE_V1_HEADER",
    "TIMESTAMP_HEADER",
    "DEFAULT_TOLERANCE_SECONDS",
    "WritError",
    "WritApiError",
    "WritApiKeyRequiredError",
    "WritInsufficientCreditsError",
    "WritPlanLimitError",
    "WritRateLimitedError",
    "Cloud",
    "AsyncCloud",
    "CloudMonitors",
    "AsyncCloudMonitors",
    "CloudAutomations",
    "AsyncCloudAutomations",
    "CloudPersonas",
    "AsyncCloudPersonas",
    "CloudBuilds",
    "AsyncCloudBuilds",
    "TERMINAL_BUILD_STATUSES",
    "WritConnectionError",
    "WritDiscoveryError",
    "WritRunTimeoutError",
    "WritTimeoutError",
    "run_row_id",
    # file assets — bindable run inputs and captured run outputs
    "file_slots",
    "FileSlot",
    "output_files",
    "OutputFile",
    "TERMINAL_EVENTS",
    # types
    "AgentStatus",
    "AgentHealth",
    "Workflow",
    "RunCompleted",
    "RunStarted",
    "CancelResult",
    "RunFeedItem",
    "RunResults",
    "RunData",
    "Monitor",
    "MonitorHistory",
    "RecentChange",
    "Selector",
    "Extractor",
    "Automation",
    "Persona",
    "SecretMeta",
    "VaultStatus",
    "StoredFile",
    "ApiKey",
    "CrawlStatus",
    "CrawlStartBody",
    "CacheStamp",
    "CrawlDataTable",
    "CrawlDefinition",
    "CrawlDefinitionList",
    "CrawlJob",
    "CrawlList",
    "SavedCrawlData",
    "SavedCrawlRun",
    "Dataset",
    "DatasetList",
    "WsTicket",
    "StartedEvent",
    "StepEvent",
    "ProgressEvent",
    "FinishedEvent",
    "ErrorEvent",
    "RunEvent",
]
